import { paths } from "@/config/paths";
import {
  BookOpenIcon,
  ArchiveBoxIcon,
  CubeIcon,
  CurrencyDollarIcon,
  LockOpenIcon,
  ShoppingBagIcon,
  BriefcaseIcon,
  BellIcon,
  DocumentChartBarIcon,
  ClipboardDocumentIcon,
  MapPinIcon,
  GlobeAltIcon,
  PhotoIcon,
  PuzzlePieceIcon,
  TruckIcon,
  StarIcon,
  ShieldExclamationIcon,
  UserGroupIcon,
} from "@heroicons/react/24/solid";
import { SidebarSection } from "./types";

import {
  CreditCard,
  History,
  LayoutDashboard,
  ShieldCheck,
  WarehouseIcon,
  CalendarRange,
  ClipboardList,
  WalletCards,
  Landmark,
  MapIcon,
} from "lucide-react";
import {
  PERMISSION_ADMIN,
  PERMISSION_INVENTORY,
  PERMISSION_ORDERS,
  PERMISSION_PRODUCT,
  PERMISSION_STORE,
  PERMISSION_WAREHOUSE,
  PERMISSION_SUPPLIER_ACCOUNTS,
  PERMISSION_SUPPLIER_ZONES,
  PERMISSION_FINANCE_SUPPLIER_CLOSURES,
  PERMISSION_ENUM,
} from "@/lib/permissions";

export const sidebarSections: SidebarSection[] = [
  {
    id: "sales",
    label: "Ventas y Pedidos",
    permissions: [
      ...PERMISSION_STORE,
      ...PERMISSION_ORDERS,
      ...PERMISSION_ADMIN,
      PERMISSION_ENUM.RETRIEVE,
      PERMISSION_ENUM.MANAGE_WHOLESALE_BUYERS,
    ],
    items: [
      {
        id: "stores",
        label: "Tiendas",
        path: paths.dashboard.stores.list,
        icon: <ShoppingBagIcon className="h-4 w-4" />,
        permissions: PERMISSION_STORE,
      },
      {
        id: "suppliers",
        label: "Proveedores",
        path: paths.dashboard.suppliers.list,
        icon: <BriefcaseIcon className="h-4 w-4" />,
        permissions: PERMISSION_ADMIN,
      },
      {
        id: "wholesale-buyers",
        label: "Compradores Mayoristas",
        path: paths.dashboard.wholesaleBuyers.list,
        icon: <UserGroupIcon className="h-4 w-4" />,
        permissions: [PERMISSION_ENUM.RETRIEVE],
      },
      {
        id: "orders",
        label: "Órdenes",
        path: paths.dashboard.orders.list,
        icon: <ClipboardDocumentIcon className="h-4 w-4" />,
        permissions: PERMISSION_ORDERS,
      },
      {
        id: "claims",
        label: "Reclamaciones",
        path: paths.dashboard.claims.list,
        icon: <ShieldExclamationIcon className="h-4 w-4" />,
        permissions: [PERMISSION_ENUM.RETRIEVE],
      },
    ],
  },
  {
    id: "catalog",
    label: "Catálogo",
    permissions: [
      ...PERMISSION_ADMIN,
      ...PERMISSION_PRODUCT,
      PERMISSION_ENUM.SUPPLIER_RETRIEVE,
      PERMISSION_ENUM.SUPPLIER_CREATE,
      PERMISSION_ENUM.SUPPLIER_UPDATE,
      PERMISSION_ENUM.SUPPLIER_DELETE,
    ],
    items: [
      {
        id: "inventory",
        label: "Inventario",
        path: paths.dashboard.inventory.all,
        icon: <ClipboardDocumentIcon className="h-4 w-4" />,
        permissions: PERMISSION_INVENTORY,
      },
      {
        id: "products",
        label: "Productos",
        path: paths.dashboard.products.list,
        icon: <ShoppingBagIcon className="h-4 w-4" />,
        permissions: PERMISSION_PRODUCT,
      },
      {
        id: "warehouses",
        label: "Almacenes",
        path: paths.dashboard.warehouses.list,
        icon: <WarehouseIcon className="h-4 w-4" />,
        permissions: PERMISSION_WAREHOUSE,
      },
      {
        id: "departments",
        label: "Departamentos",
        path: paths.dashboard.departments.list,
        icon: <ArchiveBoxIcon className="h-4 w-4" />,
        permissions: PERMISSION_ADMIN,
      },
      {
        id: "categories",
        label: "Categorías",
        path: paths.dashboard.categories.list,
        icon: <BookOpenIcon className="h-4 w-4" />,
        permissions: PERMISSION_ADMIN,
      },
      {
        id: "category-suggestions",
        label: "Sugerencias de categorías",
        path: paths.dashboard.categorySuggestions.list,
        icon: <ClipboardDocumentIcon className="h-4 w-4" />,
        permissions: [PERMISSION_ENUM.SUPPLIER_RETRIEVE],
      },
      {
        id: "brands",
        label: "Marcas",
        path: paths.dashboard.brands.list,
        icon: <CubeIcon className="h-4 w-4" />,
        permissions: [
          ...PERMISSION_ADMIN,
          PERMISSION_ENUM.SUPPLIER_CREATE,
          PERMISSION_ENUM.SUPPLIER_RETRIEVE,
          PERMISSION_ENUM.SUPPLIER_UPDATE,
          PERMISSION_ENUM.SUPPLIER_DELETE,
        ],
      },

      {
        id: "content-sections",
        label: "Secciones",
        path: paths.content.sections.list,
        icon: <PuzzlePieceIcon className="h-4 w-4" />,
        permissions: PERMISSION_ADMIN,
      },
      {
        id: "content-banners",
        label: "Banners",
        path: paths.content.banners.list,
        icon: <PhotoIcon className="h-4 w-4" />,
        permissions: PERMISSION_ADMIN,
      },
      {
        id: "static-pages",
        label: "Páginas Estáticas",
        path: paths.content.staticPages.list,
        icon: <ClipboardDocumentIcon className="h-4 w-4" />,
        permissions: PERMISSION_ADMIN,
      },
    ],
  },
  {
    id: "operations",
    label: "Operaciones",
    permissions: [
      ...PERMISSION_ADMIN,
      ...PERMISSION_INVENTORY,
      ...PERMISSION_SUPPLIER_ZONES,
      PERMISSION_ENUM.SUPPLIER_RETRIEVE,
    ],
    items: [
      {
        id: "importers",
        label: "Importadoras",
        path: paths.dashboard.importers.list,
        icon: <TruckIcon className="h-4 w-4" />,
        permissions: PERMISSION_ADMIN,
      },
      {
        id: "regions",
        label: "Regiones",
        path: paths.dashboard.regions.list,
        icon: <GlobeAltIcon className="h-4 w-4" />,
        permissions: PERMISSION_ADMIN,
      },
      {
        id: "zones",
        label: "Zonas de Entrega",
        path: paths.dashboard.zones.list,
        icon: <MapIcon className="size-4" />,
        permissions: PERMISSION_ADMIN,
      },
      {
        id: "my-zones",
        label: "Mis Zonas de Entrega",
        path: paths.provider.zones.list,
        icon: <MapIcon className="size-4" />,
        permissions: PERMISSION_SUPPLIER_ZONES,
      },
      {
        id: "my-reviews",
        label: "Mis reseñas",
        path: paths.provider.reviews.list,
        icon: <StarIcon className="h-4 w-4" />,
        permissions: [PERMISSION_ENUM.SUPPLIER_RETRIEVE],
      },
    ],
  },
  {
    id: "finance",
    label: "Finanzas",
    permissions: [
      ...PERMISSION_ADMIN,
      ...PERMISSION_FINANCE_SUPPLIER_CLOSURES,
      ...PERMISSION_SUPPLIER_ACCOUNTS,
    ],
    items: [
      {
        id: "finance-closures",
        label: "Cierres",
        path: paths.finance.closures,
        icon: <CalendarRange className="size-4" />,
        permissions: PERMISSION_FINANCE_SUPPLIER_CLOSURES,
      },
      {
        id: "finance-account-states",
        label: "Estados de cuentas",
        path: paths.finance.accountStates,
        icon: <ClipboardList className="size-4" />,
        permissions: PERMISSION_ADMIN,
      },
      {
        id: "finance-entity-accounts",
        label: "Cuentas",
        path: paths.finance.entityAccounts,
        icon: <WalletCards className="size-4" />,
        permissions: PERMISSION_ADMIN,
      },
      {
        id: "my-bank-accounts",
        label: "Mis Cuentas Bancarias",
        path: paths.provider.bankAccounts.list,
        icon: <Landmark className="size-4" />,
        permissions: PERMISSION_SUPPLIER_ACCOUNTS,
      },
      {
        id: "payment-gateway",
        label: "Pasarelas de Pago",
        path: paths.dashboard.gateways.paymentGateway,
        icon: <CreditCard className="size-4" />,
        permissions: PERMISSION_ADMIN,
      },
      {
        id: "currencies",
        label: "Monedas",
        path: paths.dashboard.currencies.list,
        icon: <CurrencyDollarIcon className="h-4 w-4" />,
        permissions: PERMISSION_ADMIN,
      },
    ],
  },
  {
    id: "admin",
    label: "Administración",
    permissions: [...PERMISSION_ADMIN],
    items: [
      {
        id: "logs",
        label: "Logs",
        path: paths.dashboard.logs.list,
        icon: <DocumentChartBarIcon className="h-4 w-4" />,
        permissions: PERMISSION_ADMIN,
      },
      {
        id: "system-info",
        label: "Información de la Tienda",
        path: paths.dashboard.systemInfo.root,
        icon: <GlobeAltIcon className="h-4 w-4" />,
        permissions: PERMISSION_ADMIN,
      },
    ],
  },
];

export const defaultExpandedSections = {
  dashboard: true,
  sales: true,
  catalog: true,
  operations: false,
  finance: false,
  admin: false,
};

export const defaultExpandedItems = {
  "invoice-management": false,
  catalog: true,
  security: true,
  logistics: true,
};
