name: Deploy to CapRover

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create .env file from secrets
        run: |
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
          echo "NEXT_PUBLIC_SSO_URL=${{ secrets.NEXT_PUBLIC_SSO_URL }}" >> .env
          echo "ENCRYPTION_SECRET=${{ secrets.ENCRYPTION_SECRET }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}" >> .env

      - name: Create deploy.tar for CapRover
        run: tar --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='deploy.tar' -cvf deploy.tar .

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAP_ROVER_SERVER }}"
          app: "${{ secrets.APP_NAME_ZAS }}"
          token: "${{ secrets.APP_TOKEN_CAP_ROVER_ZAS }}"
